# GET LIST OF COMMENTS with wrong Video id 

GET http://localhost:5000/api/v1/video/2/comments


###

# GET LIST OF COMMENTS with right Video id 

GET http://localhost:5000/api/v1/video/64da4a6895f8e95cc824e1ca/comments

###

# ADD COMMENT 

POST http://localhost:5000/api/v1/video/64da4a6895f8e95cc824e1ca/comments
Content-Type: application/json

{
  "username" : "Bondan",
  "message": "Keren"
}