# GET LIST OF PRODUCTS with wrong Video id 

GET http://localhost:3000/products
Content-Type: application/json

{
  "videoId" : "2"
}

###

# GET LIST OF PRODUCTS with right Video id 

GET http://localhost:3000/products
Content-Type: application/json

{
  "videoId" : "5f32bfb7-025b-4b6e-a2e3-d0782d0a13b1"
}