# GET LIST OF PRODUCTS with wrong Video id 

GET http://localhost:5000/api/v1/video/2/products

###

# GET LIST OF PRODUCTS with right Video id 

GET http://localhost:5000/api/v1/video/64da4a6895f8e95cc824e1ca/products

###

# ADD PRODUCT

POST http://localhost:5000/api/v1/video/64da4a6895f8e95cc824e1ca/products
Content-Type: application/json

 {
        "linkProduct": "https://www.tokopedia.com/unilever/axe-parfum-saku-dark-temptation-15ml",
        "title": "Axe Parfum Saku",
        "price": 14600,
        "imageURL": "https://images.tokopedia.net/img/cache/500-square/VqbcmM/2022/8/10/1089d8b4-ddac-4f51-8fe6-621ef4c345a8.png.webp?ect=4g"
      }