# GET LIST OF VIDEOS

GET http://localhost:5000/videos

###

# ADD VIDEO WITH BAD PAYLOAD
POST http://localhost:5000/videos
Content-Type: application/json

{
  "name": "Pasar Ponsel Surabaya",
  "title": "Oppo Reno 5",
  "videoId": "_DHtREjG0Kc",
  "linkVideo": "https://www.youtube.com/embed/_DHtREjG0Kc"
}

###

#ADD VIDEO
POST http://localhost:5000/videos
Content-Type: application/json

{
    "name": "Pasar Ponsel Surabaya",
    "title": "Oppo Reno 5",
    "videoId": "_DHtREjG0Kc",
    "linkVideo": "https://www.youtube.com/embed/_DHtREjG0Kc",
    "thumbnailURL": "https://i.ytimg.com/vi/_DHtREjG0Kc/hqdefault.jpg",
    "category": [
      "Elektronik"
    ]
}