# GET LIST OF VIDEOS

GET http://localhost:5000/api/v1/videos

###

# GET VIDEO BY ID

GET http://localhost:5000/api/v1/video/64da4a6895f8e95cc824e1ca

###

# ADD VIDEO WITH BAD PAYLOAD
POST http://localhost:5000/api/v1/videos
Content-Type: application/json

{
  "name": "Pasar Ponsel Surabaya",
  "title": "Oppo Reno 5",
  "videoId": "_DHtREjG0Kc",
  "linkVideo": "https://www.youtube.com/embed/_DHtREjG0Kc"
}

###

#ADD VIDEO
POST http://localhost:5000/api/v1/videos
Content-Type: application/json

{
    "name": "Pasar Ponsel Surabaya",
    "title": "Oppo Reno 5",
    "linkVideo": "https://www.youtube-nocookie.com/embed/_DHtREjG0Kc",
    "thumbnailURL": "https://i.ytimg.com/vi/_DHtREjG0Kc/mqdefault.jpg",
    "youtubeId": "_DHtREjG0Kc",
    "category": [
      "Elektronik"
    ]
}