# GET LIST OF VIDEOS

GET http://localhost:3000/videos

###

# ADD VIDEO WITH BAD PAYLOAD
POST http://localhost:3000/videos
Content-Type: application/json

{
  "urlThumbnail": "test thumbnail",
  "titleVideo": "test title"
}

###

#ADD VIDEO
POST http://localhost:3000/videos
Content-Type: application/json

{
  "urlThumbnail": "test thumbnail 2",
  "titleVideo": "test title 2",
  "linkVideo": "test link 2"
}